apiVersion: batch/v1
kind: Job
metadata:
  name: starting-deploy-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-100"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: quay.io/curl/curl:latest
        command:
        - curl
        - https://hq.changeover.za.net/healthz?starting_deployment
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-deploy-example-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
  label:
    thing: thing
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: quay.io/curl/curl:latest
        command:
        - curl
        - https://hq.changeover.za.net/healthz?running_migration
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-deploy-example-db-migration-long
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
  label:
    thing: thing
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: quay.io/curl/curl:latest
        command:
        - sleep
        - "30"
#---
#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: post-deploy-example-db-migration
#  annotations:
#    argocd.argoproj.io/hook: PostSync
#    argocd.argoproj.io/sync-wave: "0"
#spec:
#  template:
#    spec:
#      restartPolicy: Never
#      containers:
#      - name: migration
#        image: quay.io/curl/curl:latest
#        command:
#        - curl
#        - https://hq.changeover.za.net/healthz?finished_deploying
#---
#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: failure-example-db-migration
#  annotations:
#    argocd.argoproj.io/hook: SyncFail
#    argocd.argoproj.io/sync-wave: "0"
#spec:
#  template:
#    spec:
#      restartPolicy: Never
#      containers:
#      - name: migration
#        image: quay.io/curl/curl:latest
#        command:
#        - curl
#        - https://hq.changeover.za.net/healthz?failing_deployment
