apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  minReadySeconds: 0
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
          name: http
        env:
        - name: TEST2
          value: test2

