apiVersion: batch/v1
kind: Job
metadata:
  name: post-run-example
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: ubuntu
        command:
        - date
