apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  minReadySeconds: 0
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        thing: thing
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
          name: http
        env:
        - name: CELL
          value: eu
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: guestbook-ui
          nodeTaintsPolicy: Honor
